/*
Copyright 2024 The Aibrix Team.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/api/core/v1"
)

// ModelSpecApplyConfiguration represents an declarative configuration of the ModelSpec type for use
// with apply.
type ModelSpecApplyConfiguration struct {
	Engine   *string             `json:"engine,omitempty"`
	Template *v1.PodTemplateSpec `json:"template,omitempty"`
	Replicas *int32              `json:"replicas,omitempty"`
}

// ModelSpecApplyConfiguration constructs an declarative configuration of the ModelSpec type for use with
// apply.
func ModelSpec() *ModelSpecApplyConfiguration {
	return &ModelSpecApplyConfiguration{}
}

// WithEngine sets the Engine field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Engine field is set to the value of the last call.
func (b *ModelSpecApplyConfiguration) WithEngine(value string) *ModelSpecApplyConfiguration {
	b.Engine = &value
	return b
}

// WithTemplate sets the Template field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Template field is set to the value of the last call.
func (b *ModelSpecApplyConfiguration) WithTemplate(value v1.PodTemplateSpec) *ModelSpecApplyConfiguration {
	b.Template = &value
	return b
}

// WithReplicas sets the Replicas field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Replicas field is set to the value of the last call.
func (b *ModelSpecApplyConfiguration) WithReplicas(value int32) *ModelSpecApplyConfiguration {
	b.Replicas = &value
	return b
}
